default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: solar_development

test:
  <<: *default
  database: solar_test

production:
  <<: *default
  database: solar_production
  username:
  password:
